-- ============================================================
-- ORACLE SQL DEVELOPER SETUP SCRIPT
-- SMK Negeri 1 Dolok Sanggul - Student Database
-- Jalankan ini di Oracle SQL Developer jika migration Laravel gagal
-- ============================================================

-- 1. Hapus tabel jika sudah ada (hati-hati, data akan hilang!)
DROP TABLE STUDENTS CASCADE CONSTRAINTS;

-- 2. Buat tabel STUDENTS
CREATE TABLE STUDENTS (
    ID NUMBER(19,0) NOT NULL PRIMARY KEY,
    NISN VARCHAR2(20) NOT NULL UNIQUE,
    NAMA VARCHAR2(100) NOT NULL,
    GENDER VARCHAR2(20) NOT NULL,
    KELAS VARCHAR2(20) NOT NULL,
    JURUSAN VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'Aktif' NOT NULL,
    CREATED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NULL
);

-- 3. Buat sequence untuk auto-increment ID (Laravel ORM memerlukan ini)
DROP SEQUENCE STUDENTS_ID_SEQ;
CREATE SEQUENCE STUDENTS_ID_SEQ START WITH 1 INCREMENT BY 1;

-- 4. Buat trigger untuk auto-increment ID saat insert
CREATE OR REPLACE TRIGGER STUDENTS_ID_TRG
BEFORE INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT STUDENTS_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- 5. Insert data awal (seed)
INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456781', 'Ahmad Fauzi', 'L', 'XII', 'TKJ', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456782', 'Siti Aminah', 'P', 'XII', 'AKL', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456783', 'Budi Santoso', 'L', 'XI', 'TKJ', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456784', 'Dewi Lestari', 'P', 'XI', 'OTKP', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456785', 'Eko Prasetyo', 'L', 'X', 'TBG', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456786', 'Fitriani', 'P', 'X', 'AKL', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456787', 'Gilang Ramadhan', 'L', 'XII', 'OTKP', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO STUDENTS (NISN, NAMA, GENDER, KELAS, JURUSAN, STATUS, CREATED_AT, UPDATED_AT)
VALUES ('0023456788', 'Hani Susanti', 'P', 'XI', 'TBG', 'Aktif', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;

-- 6. Verifikasi data
SELECT * FROM STUDENTS;

